version: "3"


volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg-local:
    image: postgres:14-alpine3.20
    env_file: "local.env"
    ports:
      - "54331:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  pg-prod:
    image: postgres:14-alpine3.20
    env_file:
      - prod.env
    ports:
      - "54331:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: migration_local1.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local

  migrator-prod:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod