name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/chigvero"
  IMAGE_NAME: "auth_image"
  CONTAINER_NAME: "authService"


jobs:
  image-build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Configure Docker to use insecure registry
        run: |
          echo '{ "exec-opts": ["native.cgroupdriver=systemd"], "insecure-registries":["109.172.89.231:5000"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Check Docker configuration
        run: cat /etc/docker/daemon.json


      - name: Login to Github Container Registry
        run: | 
          docker login  -u ${{ secrets.REGISTRY_USERNAME }} -p ${{secrets.REGISTRY_PASSWORD}}  ${{env.REGISTRY}}


      - name:  Build and Push Docker Image
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest