name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/chigvero"
  IMAGE_NAME: "auth_image"
  CONTAINER_NAME: "authService"


jobs:
  image-build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to Github Container Registry
        run: |
          docker login  -u ${{ secrets.REGISTRY_USERNAME }} -p ${{secrets.REGISTRY_PASSWORD}}  ${{env.REGISTRY}}


      - name:  Build and Push Docker Image
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-pus
    steps:
      - name: Deploy to Selectel Cloud via SSH action
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Run SSH command
        run: |
          ssh root@31.129.63.115 '
          docker pull $REGISTRY/$IMAGE_NAME:latest
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          docker run -d --name $CONTAINER_NAME $REGISTRY/$IMAGE_NAME:latest